# Generated by Django 2.1.7 on 2019-02-22 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('audience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('genre', models.CharField(max_length=20)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('posterurl', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
